Hooks:PostHook(CharacterTweakData,"init","mark_all",function(self)

	self.security.priority_shout = "f42"
	self.gensec.priority_shout = "f42"
	self.cop.priority_shout = "f42"
	self.fbi.priority_shout = "f42"
	self.swat.priority_shout = "f42"
	self.heavy_swat.priority_shout = "f42"
	self.fbi_swat.priority_shout = "f42"
	self.fbi_heavy_swat.priority_shout = "f42"
	self.city_swat.priority_shout = "f42"
	self.gangster.priority_shout = "f42"
	self.biker.priority_shout = "f42"
	self.mobster.priority_shout = "f42"
	self.mobster_boss.priority_shout = "f42"
	self.hector_boss.priority_shout = "f42"
	self.hector_boss_no_armor.priority_shout = "f42"
	self.biker_boss.priority_shout = "f42"
	self.chavez_boss.priority_shout = "f42"
	self.bolivian.priority_shout = "f42"
	self.bolivian_indoors.priority_shout = "f42"
	self.ranchmanager.priority_shout = "f42"
	self.drug_lord_boss.priority_shout = "f42"
	self.drug_lord_boss_stealth.priority_shout = "f42"
	self.bolivian_indoors_mex.priority_shout = "f42"
	self.triad.priority_shout = "f42"
	self.triad_boss.priority_shout = "f42"
	self.deep_boss.priority_shout = "f42"
	self.shadow_spooc.priority_shout = "f33"
end)