managers.chat:feed_system_message(ChatManager.GAME, "#-#-#-BIG OIL ENGINE CLUES-#-#-#")
managers.chat:feed_system_message(ChatManager.GAME, "               DETERIUM")
managers.chat:feed_system_message(ChatManager.GAME, "1H + > = 2         3H + > = 12")
managers.chat:feed_system_message(ChatManager.GAME, "2H + < = 5         3H + < = 9")
managers.chat:feed_system_message(ChatManager.GAME, "                 HELIUM")
managers.chat:feed_system_message(ChatManager.GAME, "2H + > = 6         3H + > = 10")
managers.chat:feed_system_message(ChatManager.GAME, "2H + < = 3         3H + < = 7")
managers.chat:feed_system_message(ChatManager.GAME, "               NITROGEN")
managers.chat:feed_system_message(ChatManager.GAME, "1H + < = 1         2H + > = 4")
managers.chat:feed_system_message(ChatManager.GAME, "3H + > = 11       3H + < = 8")