Hooks:PostHook( StatisticsManager , "shot_fired" , "StatTrak_shot_fired" , function(self)
	StatTrak:update_screen()
end )
Hooks:PostHook( StatisticsManager , "objective_completed" , "StatTrak_objective_completed" , function(self)
	StatTrak:update_screen()
end )
Hooks:PostHook( StatisticsManager , "downed" , "StatTrak_downed" , function(self)
	StatTrak:update_screen()
end )