managers.chat:feed_system_message(ChatManager.GAME, "#-#-#-THE PD2 SECRET RIDDLES-#-#-#")
managers.chat:feed_system_message(ChatManager.GAME, " ")
managers.chat:feed_system_message(ChatManager.GAME, "Forever = CUPID             Star = GUIDE")
managers.chat:feed_system_message(ChatManager.GAME, "Words = APATE        Returns = ALGOL")
managers.chat:feed_system_message(ChatManager.GAME, "Most = GIANT             Desire = JEWEL")
managers.chat:feed_system_message(ChatManager.GAME, "Love = DANCE          Number = LAHUN")
managers.chat:feed_system_message(ChatManager.GAME, "Challenge = CHESS       Light = SHEUT")
managers.chat:feed_system_message(ChatManager.GAME, "Companion = SWORD   Land = SUMER")
managers.chat:feed_system_message(ChatManager.GAME, "Sumer = ZUMRU")
managers.chat:feed_system_message(ChatManager.GAME, " ")